### ISSUE TITLE
print stats in Reorder instead of in main

### ISSUE THREAD

**Issue by RCasatta** [RCasatta/blocks_iterator#42]
So that programs running with `iterate` instead of `main.rs` have stats too

**Comment by RCasatta** [comment]
https://github.com/RCasatta/blocks_iterator/pull/45/commits/92373e84b25de74dca44118c8903dd578b64fb1f

**Comment by dpc** [comment]
That's why I had benching as a standalone iterator step.

https://github.com/dpc/block-iter/blob/40578bb5eca918e7570b8ab82370ee88cebb7a9f/libs/main/src/bench.rs#L6

so one can insert `.bench_x()` at the end of a middle of an iterator chain and get stats. Though I now see that I forgot to make the `bench_x` be an iterator that returns the items it's benching.
